# BUDS Report 05: Review

### Table of Contents
1. <a href='#section 1'>Arithmetic + Simple Data Types</a>
2. <a href='#section 2'>Arrays</a>

In [1]:
# run this cell
from datascience import *
import numpy as np
import math
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
%matplotlib inline

## 1. Arithmetic + Simple Data Types <a id='section 1'></a>

Arithmetic is written horizontally in Python instead of in the usual format that you might be used to. Take some time to read these lines of code. Then, determine what they evaluate to. Don't forget that Python follows the rules of **PEMDAS** (parentheses, exponents, multiplication, division, addition, subtraction), evaluating function/method calls when needed. Feel free to write out each step.

<ul>
    <li><code>3 * 5**2 / 15 - (5 - 2**2)</code>
    <li><code>(22 / 2 - 2 * 5)**2 + (4 - 6 / 6)**2</code>
    <li><code>np.sum(np.arange(2, 4, 0.5) + 11)</code>
</ul>

_Written Answer:_

In [2]:
# SOLUTION
print(3*5**2/15 - (5-2**2))
print((22 / 2 - 2 * 5)**2 + (4 - 6 / 6)**2)
print(np.sum(np.arange(2, 4, 0.5) + 11))

4.0
10.0
55.0


Reading arithmetic in Python will be helpful whenever you're reading someone else's code or whenever you're debugging your own code. (**Debugging** is the process of locating and fixing errors in code.)

<div class="alert alert-warning">
<b>PRACTICE:</b> Other times, you'll be starting from scratch and coding some math that you formulated on paper. Try converting these statements into Python expressions.
    <ul>
        <li>$1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10$
        <li>$\cos(2\pi) + \sqrt{\frac{12}{3.0} * |1 - 3| * 11 - 7}$
        <li>The remainder of $\frac{96}{23}$
    </ul>
    </div>

In [ ]:
...

In [3]:
# SOLUTION
print(sum(np.arange(1, 11)))
print(math.cos(math.pi * 2) + ((12 / 3.0) * abs(1 - 3) * 11 - 7)**0.5)
print(96 % 23)

55
10.0
4


A good portion of coding is not spent writing code but rather *reading* code. Write a few sentences explaining what is being done in the following lines of code. Try to explain what data type you start with, what data type you end with, and what each part of the expression means.

Assume that we have a table `ratings` with the given column names.

<ul>
    <li><code>np.append(make_array("go", "bears"), "!")</code>
    <li><code>ratings.select("Movie Name", "Rank", "Year").relabel("Rank", "Rating").sort("Year")</code>
</ul>

_Written Answer:_

One of the last data types covered last week was booleans. **Booleans** are True or False values that correspond to 1 and 0 respectively. They use comparators like `<`, `>`, `<=`, `>=`, `==`, and `!=`. 

<div class="alert alert-warning">
    <b>PRACTICE:</b> Write statements that evaluate to <code>True</code> and use the following guidelines. You may need to add more code cells so that you can see its output.
    <ul>
        <li>A less than/greater than comparison with numbers.
        <li>An equals comparison of an integer and a float.
        <li>A less than or equal to/greater than or equal to comparison with a string with letters and a string with numbers.
        <li>A not equal to comparison between two strings that are the same except for a single lowercase/uppercase letter.
    </ul>
    </div>

In [ ]:
...

In [4]:
# SOLUTION
print(-1 < 1)
print(0 == 0.0)
print("aaa" >= "123")
print("hello" != "Hello")

True
True
True
True


<div class="alert alert-warning">
<b>PRACTICE:</b> Here, you'll combine both arithmetic and booleans. Write a line of code that returns <code>True</code> if <code>some_number</code> is divisible by <code>another_number</code> and <code>False</code> otherwise. Try changing out the values to check your answer.
    </div>

In [ ]:
some_number = 123456
another_number = 2
...

In [5]:
# SOLUTION
some_number = 123456
another_number = 2
some_number % another_number == 0

True

Working with a lot of arithmetic and different data types will usually require that we name our expressions or values to avoid re-typing everything out. Why do we avoid naming arrays as `array` or naming values as `max`?

_Written Answer:_

## 2. Arrays <a id='section 2'></a>

The following section will work with arrays and look at their properties. Create an array with the strings `"Hello"`, `"my"`, `"name"`, `"is"`, and your name.

In [ ]:
intro = ...
intro

In [6]:
# SOLUTION
intro = make_array("Hello", "my", "name", "is", "...")
intro

array(['Hello', 'my', 'name', 'is', '...'], dtype='<U5')

Recall that arrays must always be made of items of the *same* data type. When its contents are integers or floats, array arithmetic can be utilized. However, the rules change when the array's contents are strings. Answer the following questions to help shape your understanding of arrays.

Can we do array arithmetic with `intro`? Can we do arithmetic with an item contained in `intro`? What index is your name in?

_Written Answer:_

Now let's check your understanding. Try doing array arithmetic with `intro` in the cell below. Do any operations work? If so, what are they?

In [ ]:
...

In [7]:
# SOLUTION (no operations work)
intro * 3

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U5'), dtype('int64')) -> None

Now let's see whether we can do any operations on an item in `intro`.

<div class="alert alert-warning">
    <b>PRACTICE:</b> Access the "name" item and your name in <code>intro</code> and try to print out a statement that says <code>name: (your name)</code> where (your name) is replaced with your name. Be sure to follow the format exactly and use arithmetic.
    </div>
    
*Hint:* If this seems confusing, try to combine two separate strings together first. Then, repeat this process while accessing an element in `intro`.

In [ ]:
...

In [8]:
# SOLUTION
intro.item(2) + ": " + intro.item(4)

'name: ...'

<div class="alert alert-warning">
    <b>PRACTICE:</b> Now, let's try another operation on a string. Using arithmetic, try to repeat the first element in <code>intro</code> three times.
    </div>

In [ ]:
...

In [9]:
# SOLUTION
intro.item(0) * 3

'HelloHelloHello'

Although we can perform some operations on strings, they don't work on arrays of strings. It might seem odd, but that's simply something you need to watch out for.

Let's move to arrays of numbers.

<div class="alert alert-warning">
    <b>PRACTICE:</b> Find two different ways to make an array with 100, 98, 96, ..., 0 using <code>np.arange</code>. Recall that the arguments are the start number, the stop number, and the step size.
    </div>

In [ ]:
one_way = ...
one_way

In [ ]:
another_way = ...
another_way

In [10]:
# SOLUTION
one_way = np.arange(100, -1, -2)
one_way

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2,   0])

In [11]:
# SOLUTION
another_way = 100 - np.arange(0, 101, 2)
another_way

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2,   0])

<div class="alert alert-warning">
    <b>PRACTICE:</b> Write a boolean statement that checks whether <code>one_way</code> is the same array as <code>another_way</code>. Take a look at the output. What do you notice about it?
    </div>

In [ ]:
...

In [12]:
# SOLUTION
one_way == another_way

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

_Written Answer:_

In [Report 03](https://highschool.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-modules%2FBUDS-SU23&urlpath=tree%2FBUDS-SU23%2FWeek-1%2F3_Tables-Pt-1.ipynb&branch=main), you learned how to convert a single year into its decade. If you can do this process with one number, then you can do this with many numbers.

<div class="alert alert-warning">
    <b>PRACTICE:</b> For this part of the notebook, let's do something similar. Create an array with every single year you've been alive. Then, use that array to find out which years are leap years or not. The array <code>leap</code> should use a comparator in order to be an array of Boolean values.
    </div>

In [ ]:
years = ...
years

In [ ]:
leap = ...
leap

In [13]:
# SOLUTION
years = np.arange(2001, 2023, 1)
years

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [14]:
# SOLUTION
leap = years % 4 == 0
leap

array([False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False])

<div class="alert alert-warning">
    <b>PRACTICE:</b> Recall that each <code>True</code> value is equivalent to 1 and each <code>False</code> value is equivalent to 0. Find a function in the Python Reference Sheet that counts how many <code>True</code> values are in your leap years array.
    </div>

In [ ]:
num_leap = ...
num_leap

In [15]:
# SOLUTION
num_leap = np.count_nonzero(leap)
num_leap

5

This next cell will print out a summary of your findings. Replace the ellipses (`...`) with your name so that it works properly. It may seem trivial right now, but you can get a glimpse of how this concept could be helpful on a dataset with multiple data points (e.g., people).

In [16]:
# run this cell
print("... has lived through " + str(num_leap) + " leap years.")
print("The leap years ... has lived through are as follows: ")
for i in np.arange(len(years)):
    if leap.item(i):
        print(years.item(i))

... has lived through 5 leap years.
The leap years ... has lived through are as follows: 
2004
2008
2012
2016
2020


### Downloading as PDF

Download this notebook as a pdf by clicking <b><code>File > Download as > PDF via LaTeX (.pdf)</code></b>. Turn in the PDF into bCourses under the corresponding assignment.