# BUDS Report 06: Table Practice

### Table of Contents
1. <a href='#section 1'>Creating Tables</a>
2. <a href='#section 2'>Accessing Columns</a>
3. <a href='#section 3'>Column Arithmetic</a>
4. <a href='#section 4'>The CES Data Set Again</a>

In [1]:
# run this cell
from datascience import *
import numpy as np
import math
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
%matplotlib inline

## 1. Creating Tables <a id='section 1'></a>

Arrays represent individual columns, but tables allow us to compare items across rows. You can organize arrays into tables to make comparisons easier. Let's breakdown the first example (which you see in the following two code cells):
- It creates an empty table using the expression `Table()`,
- adds two columns by calling `with_columns` with four arguments (separated by commas),
- assigns the result to the name `fruits`, and finally
- evaluates `fruits` so that you can see the table.

The function `with_columns` takes in alternating strings (denoting column labels) and arrays (representing the data in those columns). The strings "fruit names" and "count" are the column labels that have been chosen, and the variables `fruit_names` and `count` are two arrays of the same length. 

In [2]:
fruit_names = make_array("apple","orange", "pineapple")
count = make_array(4, 3, 3)

In [3]:
fruits = Table().with_columns(
    "fruit names", fruit_names,
    "count", count)
fruits

fruit names | count
apple       | 4
orange      | 3
pineapple   | 3

<div class="alert alert-warning">
    <b>PRACTICE:</b> You can add more to this table by referencing the existing table <code>fruits</code>. Let's add a column named "price" using the <code>prices</code> array below. Name the new table <code>fruits_price</code>.
    </div>
    
Notice that the `prices_array` has 3 items in it, which is the same length as the number of rows in the fruits table.

In [4]:
prices = make_array(0.79, 1.10, 1.59)
prices

array([0.79, 1.1 , 1.59])

In [ ]:
fruits_price = fruits.with_column(
    "...", ...)
fruits_price

In [5]:
# SOLUTION
fruits_price = fruits.with_column(
    "price", prices)
fruits_price

fruit names | count | price
apple       | 4     | 0.79
orange      | 3     | 1.1
pineapple   | 3     | 1.59

You can also add columns to a table by inserting the array *within* `with_columns`. 

<div class="alert alert-warning">
    <b>PRACTICE:</b> Fill in the missing code, so that the table called <code>fruit_availability</code> has 4 columns. Its columns should be "fruit names", "count", "price", and "available". The column "available" represents whether the fruit is available at Store X.
    </div>

In [ ]:
fruit_availability = ...with_columns(
    "...", make_array(True, False, True)) 
fruit_availability

In [6]:
# SOLUTION
fruit_availability = fruits_price.with_columns(
    "available", make_array(True, False, True)) 
fruit_availability

fruit names | count | price | available
apple       | 4     | 0.79  | 1
orange      | 3     | 1.1   | 0
pineapple   | 3     | 1.59  | 1

<div class="alert alert-warning">
    <b>PRACTICE:</b> Recall that you can perform other operations on this new table. Sort the prices from least expensive to most expensive and call the resulting table <code>sorted_fruits</code>.
    </div>

In [ ]:
sorted_fruits = ...
sorted_fruits

In [7]:
# SOLUTION
sorted_fruits = fruit_availability.sort("price")
sorted_fruits

fruit names | count | price | available
apple       | 4     | 0.79  | 1
orange      | 3     | 1.1   | 0
pineapple   | 3     | 1.59  | 1

## 2. Accessing Columns <a id='section 2'></a>

`column` takes the column name of a table and returns the values in that column as an array.

You can get the "available" column from the `fruit_availability` table above. See the code below. It extracts the "available" column from the `fruit_availability` table as an array and gives it the name `availability_array`.

In [8]:
availability_array = fruit_availability.column("available")
availability_array

array([1, 0, 1])

Extracting columns from tables is useful because it allows us to perform calculations on columns *in* our tables.

<div class="alert alert-warning">
    <b>PRACTICE:</b> Assuming all fruits are available in Store X, you want to buy one of each fruit. How much will this cost us? Use the <code>fruits_price</code> table and not the <code>prices_array</code>. Assign the sum to the name <code>total_cost</code>.
</div>

In [ ]:
total_cost = ...
total_cost

In [9]:
# SOLUTION
total_cost = sum(fruits_price.column("price"))
total_cost

3.4800000000000004

## 3. Column Arithmetic <a id='section 3'></a>

If you perform an arithmetic operation on an array, Python will do the operation to every element of the array individually and return an array of all of the results. For example, say there was a new tax on fruit of 40 cents. You can add to the array of values like so.

In [10]:
new_prices = fruit_availability.column("price") + 0.40
new_prices

array([1.19, 1.5 , 1.99])

<div class="alert alert-warning">
    <b>PRACTICE:</b> Store X just received a new shipment of fruit and has doubled the amount of each fruit. Create an array called <code>new_count</code>, which has double the number of fruits from <code>count</code>. To do so, get the array from the <code>fruit_availability</code> table.
    </div>

In [ ]:
new_count = fruit_availability...("...") * 2
new_count

In [11]:
# SOLUTION
new_count = fruit_availability.column("count") * 2
new_count

array([8, 6, 6])

<div class="alert alert-warning">
    <b>PRACTICE:</b> Let's add this array to the <code>fruit_availability</code> table. Add the column and call it "new count". Assign this new table to the name <code>updated_fruits</code>.
    </div>

In [ ]:
updated_fruits = ...
updated_fruits

In [12]:
# SOLUTION
updated_fruits = fruit_availability.with_columns(
    "new count", new_count)
updated_fruits

fruit names | count | price | available | new count
apple       | 4     | 0.79  | 1         | 8
orange      | 3     | 1.1   | 0         | 6
pineapple   | 3     | 1.59  | 1         | 6

<div class="alert alert-warning">
    <b>PRACTICE:</b> For the final table, you only want 3 columns: "fruit names", "new count", and "price". Once you've selected only those columns, sort the prices from most expensive to least expensive.
    </div>

In [ ]:
final_fruits = updated_fruits...("...", "new count", "...").sort("...", descending = ...)
final_fruits

In [13]:
# SOLUTION
final_fruits = updated_fruits.select("fruit names", "new count", "price").sort("price", descending=True)
final_fruits

fruit names | new count | price
pineapple   | 6         | 1.59
orange      | 6         | 1.1
apple       | 8         | 0.79

## 4. The CES Data Set Again <a id='section 4'></a>

Now that you have an idea of how to update columns within a table, you can do some exploration with real-world data. Here, you'll revisit the CalEnviroScreen dataset. Reference the shared document in which your team collected background information. Feel free to look back at [Report 04](https://highschool.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fds-modules%2FBUDS-SU23&urlpath=tree%2FBUDS-SU23%2FWeek-1%2F4_Tables-Pt-2.ipynb&branch=main) or the more in-depth [CalEnviroScreen report](https://oehha.ca.gov/media/downloads/calenviroscreen/report/calenviroscreen40reportf2021.pdf).

In [14]:
ces_data = Table.read_table("ces_data_v2.csv")
ces_data

Census.Tract | CES.3.0.Score | Total.Population | California.County | Hispanic.... | White.... | African.American.... | Native.American.... | Asian.American.... | Other.... | ZIP   | Longitude | Latitude | Ozone | PM2.5 | Diesel.PM | Drinking.Water | Pesticides | Tox..Release | Traffic | Cleanup.Sites | Groundwater.Threats | Haz..Waste | Imp..Water.Bodies | Solid.Waste | Pollution.Burden | Asthma | Low.Birth.Weight | Poverty | Unemployment
6019001100   | 94.09         | 3174             | Fresno            | 65.3         | 4.2       | 24.6                 | 0.5                 | 3.5                | 1.8       | 93706 | -119.782  | 36.7097  | 0.065 | 15.4  | 48.524    | 681.2          | 2.75       | 18552        | 909.14  | 80.5          | 45.75               | 0.795      | 0                 | 21.75       | 79.96            | 131.64 | 7.44             | 76.3    | 17.6
6071001600   | 90.68         | 6133             | San Bernardino    | 91.1         | 5.8       | 0.7                  | 0.3                 | 1.4                | 0.7       | 91761 | -117.618  | 34.0578  | 0.062 | 13.31 | 38.556    | 904.66         | 1.37       | 7494.24      | 782.26  | 66.2          | 36                  | 1.25       | 5                 | 12          | 81.19            | 60.66  | 7.04             | 72.5    | 12.3
6019000200   | 85.97         | 3167             | Fresno            | 63.6         | 5.3       | 18.9                 | 0.6                 | 9.8                | 1.8       | 93706 | -119.806  | 36.7355  | 0.062 | 15.4  | 47.445    | 681.2          | 3.03       | 12454.9      | 576.52  | 22            | 30.25               | 0.2        | 0                 | 2.5         | 71.16            | 142.12 | 10.16            | 86.8    | 16.1
6077000801   | 82.49         | 6692             | San Joaquin       | 57.4         | 6         | 12.5                 | 0.3                 | 20.9               | 2.8       | 95203 | -121.315  | 37.9405  | 0.046 | 12.54 | 24.117    | 278.76         | 12.93      | 2387.78      | 1305.01 | 50.1          | 132.1               | 0.795      | 19                | 27          | 74.48            | 142.17 | 6.23             | 61.3    | 19.6
6019001500   | 82.03         | 2206             | Fresno            | 71.8         | 21.4      | 1.2                  | 0.5                 | 4.5                | 0.6       | 93725 | -119.718  | 36.6816  | 0.065 | 15.4  | 18.846    | 1000.24        | 3518.41    | 21790.7      | 435.16  | 60            | 54.2                | 13.1       | 0                 | 50.8        | 80.2             | 90.48  | 4.5              | 66.4    | 18.6
6037204920   | 80.73         | 2598             | Los Angeles       | 98.1         | 1.2       | 0.1                  | 0.1                 | 0.2                | 0.3       | 90023 | -118.197  | 34.0175  | 0.046 | 12.89 | 56.52     | 714.48         | 0          | 39040.2      | 2943.44 | 36.7          | 25                  | 4.93       | 7                 | 3.85        | 76.73            | 68.74  | 7.35             | 66.4    | 11.6
6077000300   | 80.18         | 2396             | San Joaquin       | 51.8         | 16.4      | 16.4                 | 1.3                 | 9.9                | 4.1       | 95203 | -121.302  | 37.9524  | 0.046 | 13.44 | 21.76     | 278.76         | 172.49     | 707.536      | 885.52  | 89.7          | 149.05              | 0.135      | 14                | 2.3         | 68.27            | 169.56 | 8.36             | 76.2    | 14.4
6019001000   | 80.13         | 4106             | Fresno            | 52.7         | 2.7       | 28.7                 | 0.4                 | 14.3               | 1.2       | 93706 | -119.804  | 36.6978  | 0.065 | 15.4  | 20.848    | 788.02         | 1435.93    | 6996.96      | 243.54  | 15.45         | 20                  | 0          | 0                 | 10          | 66.88            | 142.28 | 7.83             | 74.5    | 20
6037206050   | 79.03         | 2146             | Los Angeles       | 

Previously, you looked at asthma and some other indicators that you felt had some ties to asthma. Today, you'll make conversions with different measurements.

<div class="alert alert-warning">
    <b>PRACTICE:</b> Keep only the "California.County", "Total.Population", "Asthma", "Poverty", and "Unemployment" columns from the <code>ces_data</code> table. Assign this new table to the name <code>measurements</code> and be sure that the order of the columns match.
    </div>

In [ ]:
measurements = ...
measurements

In [15]:
# SOLUTIONS
measurements = ces_data.select("California.County", "Total.Population", "Asthma", "Poverty", "Unemployment")
measurements

California.County | Total.Population | Asthma | Poverty | Unemployment
Fresno            | 3174             | 131.64 | 76.3    | 17.6
San Bernardino    | 6133             | 60.66  | 72.5    | 12.3
Fresno            | 3167             | 142.12 | 86.8    | 16.1
San Joaquin       | 6692             | 142.17 | 61.3    | 19.6
Fresno            | 2206             | 90.48  | 66.4    | 18.6
Los Angeles       | 2598             | 68.74  | 66.4    | 11.6
San Joaquin       | 2396             | 169.56 | 76.2    | 14.4
Fresno            | 4106             | 142.28 | 74.5    | 20
Los Angeles       | 2146             | 58.03  | 75.7    | 28.5
Fresno            | 6343             | 107.8  | 83.4    | 23.5
... (8014 rows omitted)

This next cell focuses on cleaning the data that you have. Recall that some values could not be obtained and are denoted as `nan`. To get rid of these rows, some filtering must be done. As in Report 05, you do _not_ need to know what is happening in this cell; it's enough to know that it is getting rid of the tracts that do not have sufficient information.

In [16]:
for label in np.arange(1, 5):
    measurements = measurements.where(label, are.above_or_equal_to(0))
    
measurements

California.County | Total.Population | Asthma | Poverty | Unemployment
Fresno            | 3174             | 131.64 | 76.3    | 17.6
San Bernardino    | 6133             | 60.66  | 72.5    | 12.3
Fresno            | 3167             | 142.12 | 86.8    | 16.1
San Joaquin       | 6692             | 142.17 | 61.3    | 19.6
Fresno            | 2206             | 90.48  | 66.4    | 18.6
Los Angeles       | 2598             | 68.74  | 66.4    | 11.6
San Joaquin       | 2396             | 169.56 | 76.2    | 14.4
Fresno            | 4106             | 142.28 | 74.5    | 20
Los Angeles       | 2146             | 58.03  | 75.7    | 28.5
Fresno            | 6343             | 107.8  | 83.4    | 23.5
... (7860 rows omitted)

<div class="alert alert-warning">
    <b>PRACTICE:</b> The first change to make is within the "Asthma" column. It is currently measured in asthma-related emergency-department (ED) visits per every 10,000 ED visits. To make it more convenient, you'll be converting the values to the <i>percentage</i> of asthma-related emergency-department visits. This will be the number of asthma ED visits per 100 ED visits. Look at the following expressions below.

<ul>
    <li>Current measurement: $\frac{\# asthma}{\# total} = \frac{\# asthma}{10,000}$
    <li>Percentage: $\% asthma = \frac{\# asthma}{100}$
</ul>

Find out the calculations you would need to make to convert these values to percentages. Then assign <code>asthma_percent</code> to this array.
    </div>

In [ ]:
asthma_percent = ...
asthma_percent

In [17]:
# SOLUTION
asthma_percent = measurements.column("Asthma") / 10000 * 100
asthma_percent

array([1.3164, 0.6066, 1.4212, ..., 0.035 , 0.2197, 0.0368])

<div class="alert alert-warning">
    <b>PRACTICE:</b> We can now add it back to the <code>measurements</code> table using previous methods. Give it the name "Asthma.Percent" so that you can distinguish between the old and new values.
    </div>

In [ ]:
measurements = ...
measurements

In [18]:
# SOLUTION
measurements = measurements.with_column("Asthma.Percent", asthma_percent)
measurements

California.County | Total.Population | Asthma | Poverty | Unemployment | Asthma.Percent
Fresno            | 3174             | 131.64 | 76.3    | 17.6         | 1.3164
San Bernardino    | 6133             | 60.66  | 72.5    | 12.3         | 0.6066
Fresno            | 3167             | 142.12 | 86.8    | 16.1         | 1.4212
San Joaquin       | 6692             | 142.17 | 61.3    | 19.6         | 1.4217
Fresno            | 2206             | 90.48  | 66.4    | 18.6         | 0.9048
Los Angeles       | 2598             | 68.74  | 66.4    | 11.6         | 0.6874
San Joaquin       | 2396             | 169.56 | 76.2    | 14.4         | 1.6956
Fresno            | 4106             | 142.28 | 74.5    | 20           | 1.4228
Los Angeles       | 2146             | 58.03  | 75.7    | 28.5         | 0.5803
Fresno            | 6343             | 107.8  | 83.4    | 23.5         | 1.078
... (7860 rows omitted)

Well done converting our original measurements into something more intuitive! Changes like these happen frequently and are necessary when presenting findings to another party. It may seem tedious, but it gets easier the more you do it.

In this next section, let's explore the measurements of California as a whole. A characteristic of interest might be the poverty rate. CalEnviroScreen collected the percentage of people living below two times the poverty rate, *but* each percentage is specific to the corresponding tract. Since these percentages differ and since tracts are composed of different population sizes, you should find the total number of people living in poverty and the total population in order to find California's poverty rate. Consider the following equation.

$poverty rate = \frac{\# poverty}{\# total}$

<div class="alert alert-warning">
    <b>PRACTICE:</b> Let's start by finding the total number of people living in poverty (denoted '# poverty' in the above equation). Since "Poverty" is measured in terms of <i>percentages</i>, think of a way you can get it back to <i>counts</i>.
    </div>
    
*Hint:* You may need to look at more than one column in the table.

In [ ]:
poverty_count = ...
poverty_count

In [19]:
# SOLUTION
poverty_count = measurements.column("Total.Population") * measurements.column("Poverty")
poverty_count

array([242176.2, 444642.5, 274895.6, ...,  36965.6,  33814.8,  93507.6])

<div class="alert alert-warning">
    <b>PRACTICE:</b> Now that you have the total number of people living in poverty for each tract, you can add this data to the table. Recall the table method that adds a column to your table, and call this column "Poverty.Count".
    </div>

In [ ]:
measurements = ...
measurements

In [21]:
# SOLUTION
measurements = measurements.with_column("Poverty.Count", poverty_count)
measurements

California.County | Total.Population | Asthma | Poverty | Unemployment | Asthma.Percent | Poverty.Count
Fresno            | 3174             | 131.64 | 76.3    | 17.6         | 1.3164         | 242176
San Bernardino    | 6133             | 60.66  | 72.5    | 12.3         | 0.6066         | 444642
Fresno            | 3167             | 142.12 | 86.8    | 16.1         | 1.4212         | 274896
San Joaquin       | 6692             | 142.17 | 61.3    | 19.6         | 1.4217         | 410220
Fresno            | 2206             | 90.48  | 66.4    | 18.6         | 0.9048         | 146478
Los Angeles       | 2598             | 68.74  | 66.4    | 11.6         | 0.6874         | 172507
San Joaquin       | 2396             | 169.56 | 76.2    | 14.4         | 1.6956         | 182575
Fresno            | 4106             | 142.28 | 74.5    | 20           | 1.4228         | 305897
Los Angeles       | 2146             | 58.03  | 75.7    | 28.5         | 0.5803         | 162452
Fresno            | 6343             | 107.8  | 83.4    | 23.5         | 1.078          | 529006
... (7860 rows omitted)

<div class="alert alert-warning">
    <b>PRACTICE:</b> Finally, you can make the calculation to find the percentage of California residents living in poverty. The <code>measurements</code> table should now have the total # of people living in poverty and the total # of residents <i>per tract</i>. Before you make your calculation, remember that we are trying to divide the total # of California residents living in poverty by the total population of California.
    </div>
    
*Hint:* All of the tracts make up California, so you can aggregate all of those numbers to get the percentage.

In [ ]:
poverty_ca = ...
population_ca = ...

poverty_percentage = ...
poverty_percentage

In [22]:
# SOLUTION
poverty_ca = sum(measurements.column("Poverty.Count"))
population_ca = sum(measurements.column("Total.Population"))

poverty_percentage =  poverty_ca / population_ca
poverty_percentage

36.38284293111616

Look at the number outputted. Is it what you expected? If not, what is surprising about this value?

_Written Answer:_

### Extra Exploration (Optional)

If you find that you would like to do extra exploration, you might find the "Unemployment" data interesting to look at. Some (but not all) of the poverty rate could be explained by unemployment levels, so try to compare the two measurements. Feel free to copy and paste the code from above.

In [ ]:
unemp_count = ...
unemp_count

In [23]:
# SOLUTION
unemp_count = measurements.column("Total.Population") * measurements.column("Unemployment")
unemp_count

array([55862.4, 75435.9, 50988.7, ..., 62210.4,  2272.5, 21227.3])

In [ ]:
measurements = ...
measurements

In [24]:
# SOLUTION
measurements = measurements.with_column("Unemp.Count", unemp_count)
measurements

California.County | Total.Population | Asthma | Poverty | Unemployment | Asthma.Percent | Poverty.Count | Unemp.Count
Fresno            | 3174             | 131.64 | 76.3    | 17.6         | 1.3164         | 242176        | 55862.4
San Bernardino    | 6133             | 60.66  | 72.5    | 12.3         | 0.6066         | 444642        | 75435.9
Fresno            | 3167             | 142.12 | 86.8    | 16.1         | 1.4212         | 274896        | 50988.7
San Joaquin       | 6692             | 142.17 | 61.3    | 19.6         | 1.4217         | 410220        | 131163
Fresno            | 2206             | 90.48  | 66.4    | 18.6         | 0.9048         | 146478        | 41031.6
Los Angeles       | 2598             | 68.74  | 66.4    | 11.6         | 0.6874         | 172507        | 30136.8
San Joaquin       | 2396             | 169.56 | 76.2    | 14.4         | 1.6956         | 182575        | 34502.4
Fresno            | 4106             | 142.28 | 74.5    | 20           | 1.4228         | 305897        | 82120
Los Angeles       | 2146             | 58.03  | 75.7    | 28.5         | 0.5803         | 162452        | 61161
Fresno            | 6343             | 107.8  | 83.4    | 23.5         | 1.078          | 529006        | 149060
... (7860 rows omitted)

In [ ]:
poverty_ca = ...
population_ca = ...

poverty_percentage = ...
poverty_percentage

In [25]:
# SOLUTION
unemp_ca = sum(measurements.column("Unemp.Count"))
population_ca = sum(measurements.column("Total.Population"))

unemp_percentage = unemp_ca / population_ca
unemp_percentage

10.192648157875423

### Downloading as PDF

Download this notebook as a pdf by clicking <b><code>File > Download as > PDF via LaTeX (.pdf)</code></b>. Turn in the PDF into bCourses under the corresponding assignment.

Adapted from Data 8, Spring 2020 Lab 03 and Homework 02